permalink: /:title/
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'superscript']
gems:
  - jekyll-redirect-from
exclude: [vendor]

defaults:
  -
    scope:
      path: ""
    values:
      lang: english
      layout: default
  -
    scope:
      path: _posts/komi
    values:
      lang: коми
  -
    scope:
      path: _posts/russian
    values:
      lang: русский
nav:
  english:
    journal:
      title: "blog"
      url:   "/index.html"
    tools:
      title: "tools"
      url:   "/tools/"
    about:
      title: "project info"
      url:   "/about/"
  коми:
    journal:
      title: "блог"
      url:   "/блог-коми/"
    tools:
      title: "программаяс"
      url:   "/программаяс/"
    about:
      title: "проектысь"
      url:   "/йылысь/"
  русский:
    journal:
      title: "блог"
      url:   "/блог-рус/"
    tools:
      title: "орудие"
      url:   "/инструменты/"
    about:
      title: "проект"
      url:   "/проект/"
t:
  english:
    created: "Published on the"
    author: "by"
    description: "Website for a language documentation project…"
  коми:
    created: "Лэдзӧма"
    author: ", дасьтысь"
    description: "Туялӧм проектлӧн сайтыс…"
  русский:
    created: "Опубликовано"
    author: ", автор"
    description: "Сайт науцного проекта"